#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-spls
Version  : 2.3.2
Release  : 51
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/spls_2.3-2.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/spls_2.3-2.tar.gz
Summary  : Sparse Partial Least Squares (SPLS) Regression and
Group    : Development/Tools
License  : GPL-3.0
Requires: R-pls
BuildRequires : R-pls
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
partial least squares (SPLS) regression and classification

%prep
%setup -q -n spls
pushd ..
cp -a spls buildavx2
popd
pushd ..
cp -a spls buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1751381194

%install
export SOURCE_DATE_EPOCH=1751381194
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/spls/DESCRIPTION
/usr/lib64/R/library/spls/INDEX
/usr/lib64/R/library/spls/Meta/Rd.rds
/usr/lib64/R/library/spls/Meta/data.rds
/usr/lib64/R/library/spls/Meta/features.rds
/usr/lib64/R/library/spls/Meta/hsearch.rds
/usr/lib64/R/library/spls/Meta/links.rds
/usr/lib64/R/library/spls/Meta/nsInfo.rds
/usr/lib64/R/library/spls/Meta/package.rds
/usr/lib64/R/library/spls/Meta/vignette.rds
/usr/lib64/R/library/spls/NAMESPACE
/usr/lib64/R/library/spls/R/spls
/usr/lib64/R/library/spls/R/spls.rdb
/usr/lib64/R/library/spls/R/spls.rdx
/usr/lib64/R/library/spls/data/datalist
/usr/lib64/R/library/spls/data/lymphoma.RData
/usr/lib64/R/library/spls/data/mice.RData
/usr/lib64/R/library/spls/data/prostate.RData
/usr/lib64/R/library/spls/data/yeast.RData
/usr/lib64/R/library/spls/doc/index.html
/usr/lib64/R/library/spls/doc/spls-example.R
/usr/lib64/R/library/spls/doc/spls-example.Rnw
/usr/lib64/R/library/spls/doc/spls-example.pdf
/usr/lib64/R/library/spls/help/AnIndex
/usr/lib64/R/library/spls/help/aliases.rds
/usr/lib64/R/library/spls/help/paths.rds
/usr/lib64/R/library/spls/help/spls.rdb
/usr/lib64/R/library/spls/help/spls.rdx
/usr/lib64/R/library/spls/html/00Index.html
/usr/lib64/R/library/spls/html/R.css
/usr/lib64/R/library/spls/tests/tspls.R
/usr/lib64/R/library/spls/tests/tspls.Rout.save
